services: 
  presentation: 
    build: ./presentation 
    ports: 
      - "3000:3000" 
    volumes: 
      - ./presentation/app:/app 
    environment: 
      WATCHPACK_POLLING: "true" 
    depends_on: 
      - application 

  application: 
    build: ./application 
    ports: 
      - "8000:8000" 
    volumes: 
      - ./application:/var/www/html 
    depends_on: 
      - db

  db: 
    image: postgres:16 
    environment: 
      POSTGRES_DB: sandbox 
      POSTGRES_USER: sandbox 
      POSTGRES_PASSWORD: sandbox 
    ports: 
      - "5432:5432" 
    volumes: 
      - ./db/init:/docker-entrypoint-initdb.d 